M48
; DRILL file {KiCad 9.0.6} date 2026-01-30T19:38:50-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-30T19:38:50-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X143.605Y-73.11
X143.605Y-78.89
T2
X142.5Y-60.0
X142.5Y-127.5
X172.5Y-60.0
X172.5Y-127.5
M30
